flags = "-Wall -g -std=gnu11"
env = Environment(CC = "gcc", CCFLAGS = flags)
src = ["main.c", "oglTools.c", "fileTools.c", "error.c"]
env.Program("GlPersistentMapTest", src, LIBS = ["GL", "GLEW", "SDL2", "m"])
